import js from "@eslint/js";
import { defineConfig, globalIgnores } from "eslint/config";
import prettier from "eslint-config-prettier/flat";
import jestDom from "eslint-plugin-jest-dom";
import jsxA11y from "eslint-plugin-jsx-a11y";
import playwright from "eslint-plugin-playwright";
import react from "eslint-plugin-react";
import reactHooks from "eslint-plugin-react-hooks";
import testingLibrary from "eslint-plugin-testing-library";
import globals from "globals";
import tseslint from "typescript-eslint";

export default defineConfig([
  globalIgnores([
    "build/**",
    "dev-dist/**",
    "coverage/**",
    "playwright-report/**",
    "test-results/**",
    "blob-report/**",
    ".react-router/**",
    ".vercel/**",
    "supabase/.temp/**",
    // Generated by `npm run db:types`; regenerating is the only valid edit.
    "app/lib/supabase/database.types.ts",
    // Vendored from the shadcn registry — a re-run of `shadcn add` overwrites
    // any fixes made here, so linting them only creates churn.
    "app/components/ui/**",
  ]),

  // ── Baseline, type-aware ──────────────────────────────────────────────────
  // `projectService` resolves tsconfig.json automatically and also covers the
  // config files that sit outside the app's include globs.
  {
    files: ["**/*.{ts,tsx,mjs}"],
    extends: [
      js.configs.recommended,
      tseslint.configs.recommendedTypeChecked,
      tseslint.configs.stylisticTypeChecked,
    ],
    languageOptions: {
      parserOptions: {
        projectService: true,
        tsconfigRootDir: import.meta.dirname,
      },
    },
    rules: {
      "@typescript-eslint/consistent-type-imports": [
        "error",
        { fixStyle: "inline-type-imports" },
      ],
      "@typescript-eslint/no-unused-vars": [
        "error",
        { argsIgnorePattern: "^_", varsIgnorePattern: "^_" },
      ],
    },
  },

  // ── App source ────────────────────────────────────────────────────────────
  {
    files: ["app/**/*.{ts,tsx}", "test/**/*.{ts,tsx}"],
    extends: [
      react.configs.flat.recommended,
      react.configs.flat["jsx-runtime"],
      jsxA11y.flatConfigs.recommended,
      // The `flat` namespace is the flat-config build; the top-level keys of
      // the same name are still eslintrc-shaped.
      reactHooks.configs.flat["recommended-latest"],
    ],
    languageOptions: {
      globals: globals.browser,
    },
    settings: {
      react: { version: "detect" },
    },
    rules: {
      // TypeScript checks props; runtime propTypes are dead weight.
      "react/prop-types": "off",
    },
  },

  // ── Node-side tooling ─────────────────────────────────────────────────────
  {
    files: ["scripts/**/*.mjs", "*.config.{ts,mjs}"],
    languageOptions: {
      globals: globals.node,
    },
  },
  {
    // `.mjs` files are not part of the TypeScript program (allowJs is off), so
    // the type-aware rules have nothing to work from.
    files: ["**/*.mjs"],
    extends: [tseslint.configs.disableTypeChecked],
  },

  // ── Unit / component tests ────────────────────────────────────────────────
  {
    files: ["app/**/*.{test,spec}.{ts,tsx}", "test/**/*.{ts,tsx}"],
    extends: [
      testingLibrary.configs["flat/react"],
      jestDom.configs["flat/recommended"],
    ],
    rules: {
      // Test doubles and router stubs legitimately traffic in `any`.
      "@typescript-eslint/no-explicit-any": "off",
      "@typescript-eslint/no-unsafe-assignment": "off",
    },
  },

  // ── Playwright ────────────────────────────────────────────────────────────
  {
    files: ["e2e/**/*.{ts,tsx}"],
    extends: [playwright.configs["flat/recommended"]],
    languageOptions: {
      globals: globals.node,
    },
  },

  // Must stay last: turns off every rule Prettier owns.
  prettier,
]);
