-- 스토리는 올린 때부터 24시간 보이는 카드다. 한 장은 사진 스토리이거나 배경색 위의 글
-- 스토리이고, 둘 다 링크를 하나 달 수 있다(기능 명세 §17.6).
--
-- 사진 스토리는 다른 이미지 업로드와 같은 prepare → upload → publish 순서를 따른다.
-- prepare가 `pending` 행을 만들어 업로드할 정확한 경로를 정하고, publish가 object를 확인한 뒤
-- `ready`로 올린다. 글 스토리는 object가 없으므로 곧바로 `ready`로 만든다.

create type public.story_status as enum ('pending', 'ready');

create table public.stories (
  id bigint generated by default as identity primary key,
  profile_id bigint not null references public.profiles(id) on delete cascade,
  status public.story_status not null default 'pending',
  content text not null default '',
  -- 글 스토리의 배경. 사진 스토리에는 없다. 값은 클라이언트의 색 목록과 같은 키다.
  background text,
  image_path text unique,
  -- 레일 카드에 까는 축소본. 원본은 뷰어에서 그 장을 열 때만 받는다.
  thumbnail_path text unique,
  image_size_bytes bigint,
  image_width integer,
  image_height integer,
  link_url text,
  created_at timestamptz not null default now(),
  published_at timestamptz,
  expires_at timestamptz,
  constraint stories_content_length
    check (
      char_length(content) <= 100
      and content !~ '^[[:space:]]'
      and content !~ '[[:space:]]$'
    ),
  constraint stories_background_check
    check (background in ('blue', 'purple', 'pink', 'orange', 'green', 'dark')),
  constraint stories_link_url_check
    check (
      link_url is null
      or (char_length(link_url) <= 2048 and link_url ~ '^https?://[^[:space:]]+$')
    ),
  -- 사진과 배경은 정확히 하나다. 글 스토리는 글이 곧 내용이므로 비울 수 없다.
  constraint stories_kind_check
    check (
      (
        image_path is not null
        and thumbnail_path is not null
        and background is null
        and image_size_bytes is not null
        and image_width > 0
        and image_height > 0
      )
      or (
        image_path is null
        and thumbnail_path is null
        and background is not null
        and image_size_bytes is null
        and image_width is null
        and image_height is null
        and content ~ '[^[:space:]]'
      )
    ),
  constraint stories_publication_check
    check (
      (status = 'pending' and published_at is null and expires_at is null)
      or (
        status = 'ready'
        and published_at is not null
        and expires_at = published_at + interval '24 hours'
      )
    )
);

create index stories_active_idx
  on public.stories (expires_at desc)
  where status = 'ready';

create index stories_profile_idx
  on public.stories (profile_id, created_at);

alter table public.stories enable row level security;

revoke all on table public.stories
  from public, anon, authenticated;

create policy "stories_deny_direct_access"
on public.stories
for all
to public
using (false)
with check (false);

-- 앞뒤 공백을 지운다. `btrim`은 스페이스만 지워서 줄바꿈·탭만 적은 글이 빈 카드로 올라간다.
-- 클라이언트의 `String.prototype.trim()`과 맞춘다.
create function private.normalize_story_text(p_value text)
returns text
language sql
immutable
set search_path = ''
as $$
  select pg_catalog.regexp_replace(
    coalesce(p_value, ''), '^[[:space:]]+|[[:space:]]+$', '', 'g'
  );
$$;

revoke all on function private.normalize_story_text(text)
  from public;

-- 한 사람이 24시간 안에 올려 둘 수 있는 스토리 수의 상한. 아직 publish하지 않은 사진도 센다.
-- 상한이 없으면 업로드 경로를 반복 호출해 회수되기 전의 파일을 무제한으로 쌓을 수 있다.
create function private.story_writer_profile_id()
returns bigint
language plpgsql
security definer
set search_path = ''
as $$
declare
  caller_profile_id bigint;
  active_count integer;
begin
  -- 쓰기는 재학생과 교사만 한다. 졸업생은 읽기만 하며, 그중에서도 교사 스토리만 본다
  -- (기능 명세 §17.6). 프로필 행을 잠가 동시에 올린 스토리가 상한을 함께 넘지 못하게 한다.
  select profile.id
  into caller_profile_id
  from public.profiles as profile
  where profile.auth_user_id = auth.uid()
    and profile.status = 'accepted'
    and profile.deleted_at is null
    and profile.type in ('student', 'teacher')
  -- `no key update`면 상한 검사끼리는 순서가 잡히면서도, 이 프로필을 참조하는 다른 행의 외래
  -- 키 검사(`key share`)는 막지 않는다.
  for no key update;

  if caller_profile_id is null then
    raise exception 'student or teacher profile required'
      using errcode = '42501';
  end if;

  select count(*)
  into active_count
  from public.stories as story
  where story.profile_id = caller_profile_id
    and (
      (story.status = 'ready' and story.expires_at > now())
      -- 미완성 업로드는 정리 작업이 지우는 48시간 동안 센다. 24시간만 세면 그 사이에 한도를
      -- 다시 채워 회수되지 않은 행을 두 배로 쌓을 수 있다.
      or (story.status = 'pending' and story.created_at > now() - interval '48 hours')
    );

  if active_count >= 20 then
    raise exception 'too many active stories'
      using errcode = '54000';
  end if;

  return caller_profile_id;
end;
$$;

revoke all on function private.story_writer_profile_id()
  from public;

-- 노출은 작성자의 유형으로만 판정한다. 교사 스토리는 모두가 보고, 재학생 스토리는 학교에 있는
-- 사람만 본다. 기수는 판정에 쓰지 않는다(기능 명세 §6.6). 목록과 Storage 읽기 정책이 같은
-- 판정을 쓰도록 한곳에 둔다.
create function private.can_read_story(p_story_id bigint)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.stories as story
    join public.profiles as author
      on author.id = story.profile_id
      and author.status = 'accepted'
      and author.deleted_at is null
    join public.profiles as viewer
      on viewer.auth_user_id = auth.uid()
      and viewer.status = 'accepted'
      and viewer.deleted_at is null
    where story.id = p_story_id
      and story.status = 'ready'
      and story.expires_at > now()
      and (
        author.type = 'teacher'
        or (author.type = 'student' and viewer.type in ('student', 'teacher'))
      )
  );
$$;

revoke all on function private.can_read_story(bigint)
  from public;

create function private.can_read_story_media(p_object_path text)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.stories as story
    where p_object_path in (story.image_path, story.thumbnail_path)
      and private.can_read_story(story.id)
  );
$$;

revoke all on function private.can_read_story_media(text)
  from public;

grant execute on function private.can_read_story_media(text)
  to authenticated;

create function private.can_upload_story_media(p_object_path text)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.stories as story
    join public.profiles as profile on profile.id = story.profile_id
    where p_object_path in (story.image_path, story.thumbnail_path)
      and story.status = 'pending'
      and profile.auth_user_id = auth.uid()
      and profile.status = 'accepted'
      and profile.deleted_at is null
  );
$$;

revoke all on function private.can_upload_story_media(text)
  from public;

grant execute on function private.can_upload_story_media(text)
  to authenticated;

create function public.create_text_story(
  p_content text,
  p_background text,
  p_link_url text default null
)
returns bigint
language plpgsql
security definer
set search_path = ''
as $$
declare
  caller_profile_id bigint := private.story_writer_profile_id();
  created_id bigint;
  published timestamptz := now();
begin
  if char_length(private.normalize_story_text(p_content)) not between 1 and 100 then
    raise exception 'content must be 1 to 100 characters'
      using errcode = '22023';
  end if;

  insert into public.stories (
    profile_id, status, content, background, link_url, published_at, expires_at
  ) values (
    caller_profile_id,
    'ready',
    private.normalize_story_text(p_content),
    p_background,
    nullif(private.normalize_story_text(p_link_url), ''),
    published,
    published + interval '24 hours'
  )
  returning id into created_id;

  return created_id;
end;
$$;

revoke all on function public.create_text_story(text, text, text)
  from public, anon;

grant execute on function public.create_text_story(text, text, text)
  to authenticated;

create function public.prepare_image_story(
  p_size_bytes bigint,
  p_width integer,
  p_height integer,
  p_content text default '',
  p_link_url text default null
)
returns table (story_id bigint, object_path text, thumbnail_path text)
language plpgsql
security definer
set search_path = ''
as $$
declare
  caller_profile_id bigint := private.story_writer_profile_id();
  path text := auth.uid()::text || '/' || gen_random_uuid()::text;
  thumbnail text := path || '-thumb';
  created_id bigint;
begin
  if char_length(private.normalize_story_text(p_content)) > 100 then
    raise exception 'content must be at most 100 characters'
      using errcode = '22023';
  end if;
  -- 클라이언트 압축 정책(`screen`)과 버킷 용량 제한을 그대로 옮긴다.
  if p_size_bytes is null or p_size_bytes not between 1 and 4194304
    or p_width is null or p_height is null
    or least(p_width, p_height) < 1 or greatest(p_width, p_height) > 2048 then
    raise exception 'invalid normalized story image metadata'
      using errcode = '22023';
  end if;

  insert into public.stories (
    profile_id, content, image_path, thumbnail_path, image_size_bytes, image_width,
    image_height, link_url
  ) values (
    caller_profile_id,
    private.normalize_story_text(p_content),
    path,
    thumbnail,
    p_size_bytes,
    p_width,
    p_height,
    nullif(private.normalize_story_text(p_link_url), '')
  )
  returning id into created_id;

  return query select created_id, path, thumbnail;
end;
$$;

revoke all on function public.prepare_image_story(bigint, integer, integer, text, text)
  from public, anon;

grant execute on function public.prepare_image_story(bigint, integer, integer, text, text)
  to authenticated;

create function public.publish_image_story(p_story_id bigint)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  caller_id uuid := auth.uid();
  story public.stories;
  object_record storage.objects;
  published timestamptz := now();
begin
  select item.*
  into story
  from public.stories as item
  join public.profiles as profile
    on profile.id = item.profile_id
  where item.id = p_story_id
    and profile.auth_user_id = caller_id
    and profile.status = 'accepted'
    and profile.deleted_at is null
  for update of item;

  if story.id is null then
    raise exception 'story owner required' using errcode = '42501';
  end if;
  if story.status <> 'pending' then
    raise exception 'story is not pending' using errcode = '55000';
  end if;

  select object.*
  into object_record
  from storage.objects as object
  where object.bucket_id = 'story-media'
    and object.name = story.image_path;

  if object_record.id is null then
    raise exception 'uploaded object not found' using errcode = 'P0002';
  end if;
  if object_record.owner_id is distinct from caller_id::text then
    raise exception 'uploaded object owner does not match' using errcode = '42501';
  end if;
  if nullif(object_record.metadata ->> 'size', '')::bigint is distinct from story.image_size_bytes
    or object_record.metadata ->> 'mimetype' is distinct from 'image/webp' then
    raise exception 'uploaded object metadata does not match' using errcode = '22023';
  end if;

  -- 축소본은 크기를 미리 알리지 않지만 레일이 작성자마다 받는 파일이라 클라이언트 압축
  -- 정책(`card`)의 상한을 여기서도 지킨다. 넘으면 모든 뷰어의 홈이 무거워진다.
  if not exists (
    select 1
    from storage.objects as object
    where object.bucket_id = 'story-media'
      and object.name = story.thumbnail_path
      and object.owner_id = caller_id::text
      and object.metadata ->> 'mimetype' = 'image/webp'
      and nullif(object.metadata ->> 'size', '')::bigint <= 524288
  ) then
    raise exception 'uploaded thumbnail not found' using errcode = 'P0002';
  end if;

  update public.stories
  set status = 'ready',
    published_at = published,
    expires_at = published + interval '24 hours'
  where id = story.id;
end;
$$;

revoke all on function public.publish_image_story(bigint)
  from public, anon;

grant execute on function public.publish_image_story(bigint)
  to authenticated;

-- 작성자별로 묶어 그리므로 작성자 순서와 작성자 안의 순서를 함께 준다. 재학생 뷰어에게는 같은
-- 기수 재학생을 앞에 두고, 그 안팎에서는 가장 최근 스토리가 새로운 작성자 순서다. 한 작성자의
-- 스토리는 올린 순서대로 넘겨 본다(기능 명세 §6.6).
create function public.list_active_stories()
returns table (
  story_id bigint,
  pub_id text,
  name text,
  avatar_path text,
  content text,
  background text,
  image_path text,
  thumbnail_path text,
  image_width integer,
  image_height integer,
  link_url text,
  published_at timestamptz
)
language sql
stable
security definer
set search_path = ''
as $$
  with viewer as (
    select profile.type, profile.cohort
    from public.profiles as profile
    where profile.auth_user_id = auth.uid()
      and profile.status = 'accepted'
      and profile.deleted_at is null
  ), visible as (
    select
      story.*,
      author.pub_id,
      author.name,
      author.avatar_path,
      viewer.type = 'student'
        and author.type = 'student'
        and author.cohort = viewer.cohort as same_cohort
    from viewer
    cross join public.stories as story
    join public.profiles as author
      on author.id = story.profile_id
      and author.status = 'accepted'
      and author.deleted_at is null
    where story.status = 'ready'
      and story.expires_at > now()
      -- private.can_read_story와 같은 판정이다. 행마다 그 함수를 부르지 않으려고 풀어 쓴다.
      and (
        author.type = 'teacher'
        or (author.type = 'student' and viewer.type in ('student', 'teacher'))
      )
  )
  select
    visible.id,
    visible.pub_id,
    visible.name,
    visible.avatar_path,
    visible.content,
    visible.background,
    visible.image_path,
    visible.thumbnail_path,
    visible.image_width,
    visible.image_height,
    visible.link_url,
    visible.published_at
  from visible
  order by
    visible.same_cohort desc,
    max(visible.published_at) over (partition by visible.profile_id) desc,
    visible.profile_id,
    visible.published_at,
    visible.id;
$$;

revoke all on function public.list_active_stories()
  from public, anon;

grant execute on function public.list_active_stories()
  to authenticated;

-- 사용자 행동이 계기인 삭제라 그 자리에서 지운다. 행을 지우는 문장이 이미지 경로를 정리
-- 큐로 옮기므로 경로를 잃고 object만 남는 순간이 없다.
create function public.delete_my_story(p_story_id bigint)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  found_count integer;
begin
  with deleted as (
    delete from public.stories as story
    using public.profiles as profile
    where story.id = p_story_id
      and profile.id = story.profile_id
      and profile.auth_user_id = auth.uid()
      and profile.status = 'accepted'
      and profile.deleted_at is null
    returning story.image_path, story.thumbnail_path
  ), queued as (
    insert into private.storage_cleanup_queue as queue (bucket, object_path, reason)
    select 'story-media', path.object_path, 'story_media'
    from deleted
    cross join lateral (
      values (deleted.image_path), (deleted.thumbnail_path)
    ) as path(object_path)
    where path.object_path is not null
    on conflict (bucket, object_path) do update
      set dry_run = queue.dry_run and excluded.dry_run
  )
  select count(*) into found_count from deleted;

  if found_count = 0 then
    raise exception 'story owner required' using errcode = '42501';
  end if;
end;
$$;

revoke all on function public.delete_my_story(bigint)
  from public, anon;

grant execute on function public.delete_my_story(bigint)
  to authenticated;
