-- 하루짜리 짧은 글 하나가 전부다. 구분이나 유형을 두지 않으므로 무엇을 알리든 같은 자리에
-- 같은 모양으로 올라간다(기능 명세 §17.6).
create table public.stories (
  id bigint generated by default as identity primary key,
  profile_id bigint not null references public.profiles(id) on delete cascade,
  content text not null,
  created_at timestamptz not null default now(),
  constraint stories_content_length
    check (char_length(btrim(content)) between 2 and 100)
);

alter table public.stories enable row level security;

revoke all on table public.stories
  from public, anon, authenticated;

create policy "stories_deny_direct_access"
on public.stories
for all
to public
using (false)
with check (false);

create function public.set_my_story(p_content text)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  caller_profile_id bigint;
  normalized_content text := btrim(coalesce(p_content, ''));
  kst_date date;
  day_start timestamptz;
  day_end timestamptz;
begin
  if char_length(normalized_content) not between 2 and 100 then
    raise exception 'content must be between 2 and 100 characters'
      using errcode = '22023';
  end if;

  -- 쓰기는 재학생과 교사만 한다. 졸업생은 읽기만 하며, 그중에서도 교사 스토리만 본다
  -- (기능 명세 §17.6).
  select profile.id
  into caller_profile_id
  from public.profiles as profile
  where profile.auth_user_id = auth.uid()
    and profile.status = 'accepted'
    and profile.deleted_at is null
    and profile.type in ('student', 'teacher');

  if caller_profile_id is null then
    raise exception 'student or teacher profile required'
      using errcode = '42501';
  end if;

  kst_date := (now() at time zone 'Asia/Seoul')::date;
  day_start := kst_date::timestamp at time zone 'Asia/Seoul';
  day_end := (kst_date + 1)::timestamp at time zone 'Asia/Seoul';

  delete from public.stories
  where profile_id = caller_profile_id
    and created_at >= day_start
    and created_at < day_end;

  insert into public.stories (profile_id, content)
  values (caller_profile_id, normalized_content);
end;
$$;

revoke all on function public.set_my_story(text)
  from public, anon;

grant execute on function public.set_my_story(text)
  to authenticated;

create function public.list_today_stories()
returns table (
  pub_id text,
  name text,
  avatar_path text,
  content text
)
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  viewer_type public.profile_type;
  kst_date date;
  day_start timestamptz;
  day_end timestamptz;
begin
  select profile.type
  into viewer_type
  from public.profiles as profile
  where profile.auth_user_id = auth.uid()
    and profile.status = 'accepted'
    and profile.deleted_at is null;

  if viewer_type is null then
    return;
  end if;

  kst_date := (now() at time zone 'Asia/Seoul')::date;
  day_start := kst_date::timestamp at time zone 'Asia/Seoul';
  day_end := (kst_date + 1)::timestamp at time zone 'Asia/Seoul';

  return query
  select
    author.pub_id,
    author.name,
    author.avatar_path,
    story.content
  from public.stories as story
  join public.profiles as author
    on author.id = story.profile_id
  where author.status = 'accepted'
    and author.deleted_at is null
    -- 교사 스토리는 모두가 보고, 재학생 스토리는 학교에 있는 사람만 본다. 기수는 판정에
    -- 쓰지 않는다 (기능 명세 §6.6).
    and (
      author.type = 'teacher'
      or (
        author.type = 'student'
        and viewer_type in ('student', 'teacher')
      )
    )
    and story.created_at >= day_start
    and story.created_at < day_end
  order by story.created_at desc, story.id desc;
end;
$$;

revoke all on function public.list_today_stories()
  from public, anon;

grant execute on function public.list_today_stories()
  to authenticated;

create function public.delete_my_story()
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  caller_profile_id bigint;
  kst_date date;
  day_start timestamptz;
  day_end timestamptz;
begin
  select profile.id
  into caller_profile_id
  from public.profiles as profile
  where profile.auth_user_id = auth.uid()
    and profile.status = 'accepted'
    and profile.deleted_at is null
    and profile.type in ('student', 'teacher');

  if caller_profile_id is null then
    raise exception 'student or teacher profile required'
      using errcode = '42501';
  end if;

  kst_date := (now() at time zone 'Asia/Seoul')::date;
  day_start := kst_date::timestamp at time zone 'Asia/Seoul';
  day_end := (kst_date + 1)::timestamp at time zone 'Asia/Seoul';

  delete from public.stories
  where profile_id = caller_profile_id
    and created_at >= day_start
    and created_at < day_end;
end;
$$;

revoke all on function public.delete_my_story()
  from public, anon;

grant execute on function public.delete_my_story()
  to authenticated;
