create table public.student_absences (
  id bigint generated by default as identity primary key,
  profile_id bigint not null references public.profiles(id) on delete cascade,
  reason text not null,
  created_at timestamptz not null default now(),
  constraint student_absences_reason_length
    check (char_length(btrim(reason)) between 2 and 100)
);

alter table public.student_absences enable row level security;

revoke all on table public.student_absences
  from public, anon, authenticated;

create function public.set_my_absence(p_reason text)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  caller_profile_id bigint;
  normalized_reason text := btrim(coalesce(p_reason, ''));
  kst_date date;
  day_start timestamptz;
  day_end timestamptz;
begin
  if char_length(normalized_reason) not between 2 and 100 then
    raise exception 'reason must be between 2 and 100 characters'
      using errcode = '22023';
  end if;

  select profile.id
  into caller_profile_id
  from public.profiles as profile
  where profile.auth_user_id = auth.uid()
    and profile.status = 'accepted'
    and profile.deleted_at is null
    and profile.type = 'student'
    and profile.cohort is not null;

  if caller_profile_id is null then
    raise exception 'student profile required'
      using errcode = '42501';
  end if;

  kst_date := (now() at time zone 'Asia/Seoul')::date;
  day_start := kst_date::timestamp at time zone 'Asia/Seoul';
  day_end := (kst_date + 1)::timestamp at time zone 'Asia/Seoul';

  delete from public.student_absences
  where profile_id = caller_profile_id
    and created_at >= day_start
    and created_at < day_end;

  insert into public.student_absences (
    profile_id,
    reason
  )
  values (
    caller_profile_id,
    normalized_reason
  );
end;
$$;

revoke all on function public.set_my_absence(text)
  from public, anon;

grant execute on function public.set_my_absence(text)
  to authenticated;

create function public.list_today_absences()
returns table (
  pub_id text,
  name text,
  avatar_path text,
  reason text
)
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  viewer_cohort integer;
  kst_date date;
  day_start timestamptz;
  day_end timestamptz;
begin
  select
    profile.cohort
      + case when profile.is_returning_student then 1 else 0 end
  into viewer_cohort
  from public.profiles as profile
  where profile.auth_user_id = auth.uid()
    and profile.status = 'accepted'
    and profile.deleted_at is null
    and profile.type = 'student';

  if viewer_cohort is null then
    return;
  end if;

  kst_date := (now() at time zone 'Asia/Seoul')::date;
  day_start := kst_date::timestamp at time zone 'Asia/Seoul';
  day_end := (kst_date + 1)::timestamp at time zone 'Asia/Seoul';

  return query
  select
    author.pub_id,
    author.name,
    author.avatar_path,
    absence.reason
  from public.student_absences as absence
  join public.profiles as author
    on author.id = absence.profile_id
  where author.status = 'accepted'
    and author.deleted_at is null
    and author.type = 'student'
    and (
      author.cohort
        + case when author.is_returning_student then 1 else 0 end
    ) = viewer_cohort
    and absence.created_at >= day_start
    and absence.created_at < day_end
  order by absence.created_at desc, absence.id desc;
end;
$$;

revoke all on function public.list_today_absences()
  from public, anon;

grant execute on function public.list_today_absences()
  to authenticated;

create function public.delete_my_absence()
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  caller_profile_id bigint;
  kst_date date;
  day_start timestamptz;
  day_end timestamptz;
begin
  select profile.id
  into caller_profile_id
  from public.profiles as profile
  where profile.auth_user_id = auth.uid()
    and profile.status = 'accepted'
    and profile.deleted_at is null
    and profile.type = 'student'
    and profile.cohort is not null;

  if caller_profile_id is null then
    raise exception 'student profile required'
      using errcode = '42501';
  end if;

  kst_date := (now() at time zone 'Asia/Seoul')::date;
  day_start := kst_date::timestamp at time zone 'Asia/Seoul';
  day_end := (kst_date + 1)::timestamp at time zone 'Asia/Seoul';

  delete from public.student_absences
  where profile_id = caller_profile_id
    and created_at >= day_start
    and created_at < day_end;
end;
$$;

revoke all on function public.delete_my_absence()
  from public, anon;

grant execute on function public.delete_my_absence()
  to authenticated;
