import {
  index,
  layout,
  route,
  type RouteConfig,
} from "@react-router/dev/routes";

export default [
  route("login", "routes/auth/login.tsx"),
  route("signup", "routes/auth/signup.tsx"),
  route("forgot-password", "routes/auth/forgot-password.tsx"),
  route("setup", "routes/auth/setup.tsx"),
  route("pending", "routes/auth/pending.tsx"),
  route("blocked", "routes/auth/blocked.tsx"),
  route("logout", "routes/auth/logout.tsx"),
  route("noti/open/:notificationId", "routes/notification-open.tsx"),
  route("theme", "routes/theme.tsx"),
  layout("routes/app/gate.tsx", [
    layout("routes/app/layout.tsx", [
      index("routes/app/home.tsx"),
      route("feed/posts/:postId", "routes/app/feed/post-data.ts"),
      route("profile", "routes/app/profile/index.tsx"),
      route("noti", "routes/app/notifications.tsx"),
      route("noti/settings", "routes/app/notification-settings.tsx"),
      route("menu", "routes/app/menu/index.tsx"),
      route("menu/licenses", "routes/app/menu/licenses.tsx"),
      route("menu/birthdays", "routes/app/menu/birthdays.tsx"),
      route("menu/meal", "routes/app/menu/meal.tsx"),
      route("menu/absence", "routes/app/menu/absence.tsx"),
      route("menu/password", "routes/app/menu/password.tsx"),
      route("menu/settings", "routes/app/menu/settings.tsx"),
      route("menu/settings/lab", "routes/app/menu/settings-lab.tsx"),
      route("menu/timetable", "routes/app/menu/timetable.tsx"),
      route("util/gongang", "routes/app/util/gongang.tsx"),
      route("util/gongang/manage", "routes/app/util/gongang-manage.tsx"),
      route("util/karaoke", "routes/app/util/karaoke.tsx"),
      route("groups", "routes/app/groups/index.tsx"),
      route("groups/discover", "routes/app/groups/discover.tsx"),
      route("groups/member-page", "routes/app/groups/member-page.ts"),
      route("groups/report-page", "routes/app/groups/report-page.ts"),
      route("clubs", "routes/app/clubs/index.tsx"),
      route("invite/:token", "routes/app/invite.tsx"),
      route("profile/:pubId", "routes/app/profile/detail.tsx", [
        route("posts/new", "routes/app/profile/post-new.tsx"),
        route("posts/:postId", "routes/app/profile/post.tsx"),
        route("posts/:postId/edit", "routes/app/profile/post-edit.tsx"),
      ]),
      route("profile/:pubId/edit", "routes/app/profile/edit.tsx"),
      route("groups/create", "routes/app/groups/create.tsx"),
      route("groups/:slug", "routes/app/groups/detail.tsx", [
        route("posts/new", "routes/app/groups/post-new.tsx"),
        route("posts/:postId", "routes/app/groups/post.tsx"),
        route("posts/:postId/edit", "routes/app/groups/post-edit.tsx"),
      ]),
      route("clubs/:clubId", "routes/app/clubs/detail.tsx"),
      route("admin", "routes/app/admin/index.tsx"),
      route("admin/approvals", "routes/app/admin/approvals.tsx"),
      route("admin/gongang-managers", "routes/app/admin/gongang-managers.tsx"),
      route("admin/app-admins", "routes/app/admin/app-admins.tsx"),
    ]),
    layout("routes/messenger/layout.tsx", [
      route("messenger", "routes/messenger/index.tsx", [
        route(":roomId", "routes/messenger/room.tsx"),
      ]),
    ]),
  ]),
  route("*", "routes/catch-all.tsx"),
] satisfies RouteConfig;
