SET local check_function_bodies = off;

-- Keep bucket security limits reproducible even when the local Storage API is
-- temporarily unavailable while `supabase db reset` synchronizes config.toml.
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('story-media', 'story-media', false, 4194304, array['image/webp'])
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

DROP VIEW "private"."referenced_storage_objects";

ALTER TABLE "private"."storage_cleanup_queue"
  DROP CONSTRAINT "storage_cleanup_queue_reason_check";

DROP FUNCTION "public"."delete_my_story"();

DROP FUNCTION "public"."list_today_stories"();

DROP FUNCTION "public"."set_my_story"(text);

-- 하루 한 줄이던 스토리를 사진·글 카드로 바꾼다. 기존 행은 없고 모양이 전부 바뀌므로 고쳐 쓰지
-- 않고 새로 만든다.
DROP TABLE "public"."stories";

create type public.story_status as enum ('pending', 'ready');

create table public.stories (
  id bigint generated by default as identity primary key,
  profile_id bigint not null references public.profiles(id) on delete cascade,
  status public.story_status not null default 'pending',
  content text not null default '',
  -- 글 스토리의 배경. 사진 스토리에는 없다. 값은 클라이언트의 색 목록과 같은 키다.
  background text,
  image_path text unique,
  -- 레일 카드에 까는 축소본. 원본은 뷰어에서 그 장을 열 때만 받는다.
  thumbnail_path text unique,
  image_size_bytes bigint,
  image_width integer,
  image_height integer,
  link_url text,
  created_at timestamptz not null default now(),
  published_at timestamptz,
  expires_at timestamptz,
  constraint stories_content_length
    check (char_length(content) <= 100 and content = btrim(content)),
  constraint stories_background_check
    check (background in ('blue', 'purple', 'pink', 'orange', 'green', 'dark')),
  constraint stories_link_url_check
    check (
      link_url is null
      or (char_length(link_url) <= 2048 and link_url ~ '^https?://[^[:space:]]+$')
    ),
  -- 사진과 배경은 정확히 하나다. 글 스토리는 글이 곧 내용이므로 비울 수 없다.
  constraint stories_kind_check
    check (
      (
        image_path is not null
        and thumbnail_path is not null
        and background is null
        and image_size_bytes is not null
        and image_width > 0
        and image_height > 0
      )
      or (
        image_path is null
        and thumbnail_path is null
        and background is not null
        and image_size_bytes is null
        and image_width is null
        and image_height is null
        and char_length(content) >= 1
      )
    ),
  constraint stories_publication_check
    check (
      (status = 'pending' and published_at is null and expires_at is null)
      or (
        status = 'ready'
        and published_at is not null
        and expires_at = published_at + interval '24 hours'
      )
    )
);

create index stories_active_idx
  on public.stories (expires_at desc)
  where status = 'ready';

create index stories_profile_idx
  on public.stories (profile_id, created_at);

alter table public.stories enable row level security;

revoke all on table public.stories
  from public, anon, authenticated;

create policy "stories_deny_direct_access"
on public.stories
for all
to public
using (false)
with check (false);

CREATE OR REPLACE FUNCTION private.can_read_story (
  p_story_id bigint
)
  RETURNS boolean
  LANGUAGE sql
  STABLE
  SECURITY DEFINER
  SET search_path TO ''
  AS $function$
  select exists (
    select 1
    from public.stories as story
    join public.profiles as author
      on author.id = story.profile_id
      and author.status = 'accepted'
      and author.deleted_at is null
    join public.profiles as viewer
      on viewer.auth_user_id = auth.uid()
      and viewer.status = 'accepted'
      and viewer.deleted_at is null
    where story.id = p_story_id
      and story.status = 'ready'
      and story.expires_at > now()
      and (
        author.type = 'teacher'
        or (author.type = 'student' and viewer.type in ('student', 'teacher'))
      )
  );
$function$;

CREATE OR REPLACE FUNCTION private.can_read_story_media (
  p_object_path text
)
  RETURNS boolean
  LANGUAGE sql
  STABLE
  SECURITY DEFINER
  SET search_path TO ''
  AS $function$
  select exists (
    select 1
    from public.stories as story
    where p_object_path in (story.image_path, story.thumbnail_path)
      and private.can_read_story(story.id)
  );
$function$;

CREATE OR REPLACE FUNCTION private.can_upload_story_media (
  p_object_path text
)
  RETURNS boolean
  LANGUAGE sql
  STABLE
  SECURITY DEFINER
  SET search_path TO ''
  AS $function$
  select exists (
    select 1
    from public.stories as story
    join public.profiles as profile on profile.id = story.profile_id
    where p_object_path in (story.image_path, story.thumbnail_path)
      and story.status = 'pending'
      and profile.auth_user_id = auth.uid()
      and profile.status = 'accepted'
      and profile.deleted_at is null
  );
$function$;

CREATE OR REPLACE FUNCTION private.cleanup_expired_records()
  RETURNS bigint
  LANGUAGE plpgsql
  SECURITY DEFINER
  SET search_path TO ''
  AS $function$
declare
  removed bigint := 0;
  affected bigint;
  korea_today date := (now() at time zone 'Asia/Seoul')::date;
begin
  -- 스토리는 만료되면 읽는 경로가 없다(기능 명세 §17.6). publish하지 못한 사진 스토리는 48시간을
  -- 기다린다. Storage 2층 스윕과 같은 유예라 업로드 중인 행을 지우지 않는다. 행을 지우는 문장이
  -- 이미지 경로를 정리 큐로 옮긴다.
  with expired as (
    delete from public.stories as story
    where (story.status = 'ready' and story.expires_at <= now())
      or (story.status = 'pending' and story.created_at <= now() - interval '48 hours')
    returning story.image_path, story.thumbnail_path
  ), queued as (
    insert into private.storage_cleanup_queue as queue (bucket, object_path, reason)
    select 'story-media', path.object_path, 'story_media'
    from expired
    cross join lateral (
      values (expired.image_path), (expired.thumbnail_path)
    ) as path(object_path)
    where path.object_path is not null
    on conflict (bucket, object_path) do update
      set dry_run = queue.dry_run and excluded.dry_run
  )
  select count(*) into affected from expired;
  removed := removed + affected;

  -- 예약은 끝난 뒤 2주까지 남긴다. 반복 예약은 종료일이 정해지기 전까지 지우지 않는다.
  delete from public.utility_reservations as reservation
  where case
      when reservation.recurring then reservation.recurring_until
      else reservation.reservation_date
    end < korea_today - 14;
  get diagnostics affected = row_count;
  removed := removed + affected;

  delete from public.gongang_schedule
  where schedule_date < korea_today - 14;
  get diagnostics affected = row_count;
  removed := removed + affected;

  -- 랭킹 이벤트는 append-only 라 정리 경로임을 밝혀야 지울 수 있다(삭제 및 보존 정책 §7.4).
  perform pg_catalog.set_config('app.feed_event_purge', 'on', true);

  -- 반응 이벤트는 발행 후 6시간 이내 게시물에만 합산된다. 그보다 오래된 것은 어떤 조회에도 잡히지
  -- 않는다. 경계를 넉넉히 두려고 하루를 남긴다.
  delete from private.post_reaction_count_events
  where occurred_at < now() - interval '24 hours';
  get diagnostics affected = row_count;
  removed := removed + affected;

  -- `#업` 이벤트는 게시물당 가장 최근 하나만 읽는다. 1시간 중복 방지 검사도 최근 구간만 보므로
  -- 최신 한 건을 남기면 두 조회가 모두 그대로 동작한다. 나머지는 죽은 데이터다.
  delete from private.feed_bump_events as bump
  where exists (
    select 1
    from private.feed_bump_events as newer
    where newer.post_id = bump.post_id
      and (newer.effective_at, newer.id) > (bump.effective_at, bump.id)
  );
  get diagnostics affected = row_count;
  removed := removed + affected;

  perform pg_catalog.set_config('app.feed_event_purge', 'off', true);

  return removed;
end;
$function$;

CREATE OR REPLACE FUNCTION private.story_writer_profile_id()
  RETURNS bigint
  LANGUAGE plpgsql
  SECURITY DEFINER
  SET search_path TO ''
  AS $function$
declare
  caller_profile_id bigint;
  active_count integer;
begin
  -- 쓰기는 재학생과 교사만 한다. 졸업생은 읽기만 하며, 그중에서도 교사 스토리만 본다
  -- (기능 명세 §17.6). 프로필 행을 잠가 동시에 올린 스토리가 상한을 함께 넘지 못하게 한다.
  select profile.id
  into caller_profile_id
  from public.profiles as profile
  where profile.auth_user_id = auth.uid()
    and profile.status = 'accepted'
    and profile.deleted_at is null
    and profile.type in ('student', 'teacher')
  for update;

  if caller_profile_id is null then
    raise exception 'student or teacher profile required'
      using errcode = '42501';
  end if;

  select count(*)
  into active_count
  from public.stories as story
  where story.profile_id = caller_profile_id
    and (
      (story.status = 'ready' and story.expires_at > now())
      or (story.status = 'pending' and story.created_at > now() - interval '24 hours')
    );

  if active_count >= 20 then
    raise exception 'too many active stories'
      using errcode = '54000';
  end if;

  return caller_profile_id;
end;
$function$;

CREATE OR REPLACE FUNCTION private.sweep_unreferenced_storage_objects (
  p_dry_run boolean DEFAULT true,
  p_limit   integer DEFAULT 1000
)
  RETURNS bigint
  LANGUAGE plpgsql
  SECURITY DEFINER
  SET search_path TO ''
  AS $function$
declare
  enqueued bigint;
begin
  if p_limit not between 1 and 10000 then
    raise exception 'invalid sweep limit' using errcode = '22023';
  end if;

  with unreferenced as (
    select object.bucket_id as bucket, object.name as object_path
    from storage.objects as object
    where object.bucket_id in ('profile-media', 'group-media', 'post-attachments', 'story-media')
      and object.created_at <= now() - interval '48 hours'
      and not coalesce(object.is_delete_marker, false)
      and not exists (
        select 1
        from private.referenced_storage_objects as reference
        where reference.bucket = object.bucket_id
          and reference.object_path = object.name
      )
    order by object.created_at
    limit p_limit
  )
  insert into private.storage_cleanup_queue as queue (bucket, object_path, reason, dry_run)
  select
    unreferenced.bucket,
    unreferenced.object_path,
    'unreferenced_sweep',
    coalesce(p_dry_run, true)
  from unreferenced
  on conflict (bucket, object_path) do update
    set dry_run = queue.dry_run and excluded.dry_run;
  get diagnostics enqueued = row_count;

  return enqueued;
end;
$function$;

CREATE OR REPLACE FUNCTION public.create_text_story (
  p_content    text,
  p_background text,
  p_link_url   text DEFAULT NULL::text
)
  RETURNS bigint
  LANGUAGE plpgsql
  SECURITY DEFINER
  SET search_path TO ''
  AS $function$
declare
  caller_profile_id bigint := private.story_writer_profile_id();
  created_id bigint;
  published timestamptz := now();
begin
  if char_length(btrim(coalesce(p_content, ''))) not between 1 and 100 then
    raise exception 'content must be 1 to 100 characters'
      using errcode = '22023';
  end if;

  insert into public.stories (
    profile_id, status, content, background, link_url, published_at, expires_at
  ) values (
    caller_profile_id,
    'ready',
    btrim(p_content),
    p_background,
    nullif(btrim(coalesce(p_link_url, '')), ''),
    published,
    published + interval '24 hours'
  )
  returning id into created_id;

  return created_id;
end;
$function$;

CREATE OR REPLACE FUNCTION public.delete_my_story (
  p_story_id bigint
)
  RETURNS void
  LANGUAGE plpgsql
  SECURITY DEFINER
  SET search_path TO ''
  AS $function$
declare
  found_count integer;
begin
  with deleted as (
    delete from public.stories as story
    using public.profiles as profile
    where story.id = p_story_id
      and profile.id = story.profile_id
      and profile.auth_user_id = auth.uid()
      and profile.status = 'accepted'
      and profile.deleted_at is null
    returning story.image_path, story.thumbnail_path
  ), queued as (
    insert into private.storage_cleanup_queue as queue (bucket, object_path, reason)
    select 'story-media', path.object_path, 'story_media'
    from deleted
    cross join lateral (
      values (deleted.image_path), (deleted.thumbnail_path)
    ) as path(object_path)
    where path.object_path is not null
    on conflict (bucket, object_path) do update
      set dry_run = queue.dry_run and excluded.dry_run
  )
  select count(*) into found_count from deleted;

  if found_count = 0 then
    raise exception 'story owner required' using errcode = '42501';
  end if;
end;
$function$;

CREATE OR REPLACE FUNCTION public.list_active_stories()
  RETURNS TABLE (
    story_id       bigint,
    pub_id         text,
    name           text,
    avatar_path    text,
    content        text,
    background     text,
    image_path     text,
    thumbnail_path text,
    image_width    integer,
    image_height   integer,
    link_url       text,
    published_at   timestamp with time zone
  )
  LANGUAGE sql
  STABLE
  SECURITY DEFINER
  SET search_path TO ''
  AS $function$
  with viewer as (
    select profile.type, profile.cohort
    from public.profiles as profile
    where profile.auth_user_id = auth.uid()
      and profile.status = 'accepted'
      and profile.deleted_at is null
  ), visible as (
    select
      story.*,
      author.pub_id,
      author.name,
      author.avatar_path,
      viewer.type = 'student'
        and author.type = 'student'
        and author.cohort = viewer.cohort as same_cohort
    from viewer
    cross join public.stories as story
    join public.profiles as author
      on author.id = story.profile_id
      and author.status = 'accepted'
      and author.deleted_at is null
    where story.status = 'ready'
      and story.expires_at > now()
      -- private.can_read_story와 같은 판정이다. 행마다 그 함수를 부르지 않으려고 풀어 쓴다.
      and (
        author.type = 'teacher'
        or (author.type = 'student' and viewer.type in ('student', 'teacher'))
      )
  )
  select
    visible.id,
    visible.pub_id,
    visible.name,
    visible.avatar_path,
    visible.content,
    visible.background,
    visible.image_path,
    visible.thumbnail_path,
    visible.image_width,
    visible.image_height,
    visible.link_url,
    visible.published_at
  from visible
  order by
    visible.same_cohort desc,
    max(visible.published_at) over (partition by visible.profile_id) desc,
    visible.profile_id,
    visible.published_at,
    visible.id;
$function$;

CREATE OR REPLACE FUNCTION public.prepare_image_story (
  p_size_bytes bigint,
  p_width      integer,
  p_height     integer,
  p_content    text    DEFAULT ''::text,
  p_link_url   text    DEFAULT NULL::text
)
  RETURNS TABLE (
    story_id       bigint,
    object_path    text,
    thumbnail_path text
  )
  LANGUAGE plpgsql
  SECURITY DEFINER
  SET search_path TO ''
  AS $function$
declare
  caller_profile_id bigint := private.story_writer_profile_id();
  path text := auth.uid()::text || '/' || gen_random_uuid()::text;
  thumbnail text := path || '-thumb';
  created_id bigint;
begin
  if char_length(btrim(coalesce(p_content, ''))) > 100 then
    raise exception 'content must be at most 100 characters'
      using errcode = '22023';
  end if;
  -- 클라이언트 압축 정책(`screen`)과 버킷 용량 제한을 그대로 옮긴다.
  if p_size_bytes is null or p_size_bytes not between 1 and 4194304
    or p_width is null or p_height is null
    or least(p_width, p_height) < 1 or greatest(p_width, p_height) > 2048 then
    raise exception 'invalid normalized story image metadata'
      using errcode = '22023';
  end if;

  insert into public.stories (
    profile_id, content, image_path, thumbnail_path, image_size_bytes, image_width,
    image_height, link_url
  ) values (
    caller_profile_id,
    btrim(coalesce(p_content, '')),
    path,
    thumbnail,
    p_size_bytes,
    p_width,
    p_height,
    nullif(btrim(coalesce(p_link_url, '')), '')
  )
  returning id into created_id;

  return query select created_id, path, thumbnail;
end;
$function$;

CREATE OR REPLACE FUNCTION public.publish_image_story (
  p_story_id bigint
)
  RETURNS void
  LANGUAGE plpgsql
  SECURITY DEFINER
  SET search_path TO ''
  AS $function$
declare
  caller_id uuid := auth.uid();
  story public.stories;
  object_record storage.objects;
  published timestamptz := now();
begin
  select item.*
  into story
  from public.stories as item
  join public.profiles as profile
    on profile.id = item.profile_id
  where item.id = p_story_id
    and profile.auth_user_id = caller_id
    and profile.status = 'accepted'
    and profile.deleted_at is null
  for update of item;

  if story.id is null then
    raise exception 'story owner required' using errcode = '42501';
  end if;
  if story.status <> 'pending' then
    raise exception 'story is not pending' using errcode = '55000';
  end if;

  select object.*
  into object_record
  from storage.objects as object
  where object.bucket_id = 'story-media'
    and object.name = story.image_path;

  if object_record.id is null then
    raise exception 'uploaded object not found' using errcode = 'P0002';
  end if;
  if object_record.owner_id is distinct from caller_id::text then
    raise exception 'uploaded object owner does not match' using errcode = '42501';
  end if;
  if nullif(object_record.metadata ->> 'size', '')::bigint is distinct from story.image_size_bytes
    or object_record.metadata ->> 'mimetype' is distinct from 'image/webp' then
    raise exception 'uploaded object metadata does not match' using errcode = '22023';
  end if;

  -- 축소본은 크기를 미리 알리지 않는다. 버킷 제한과 MIME만 맞으면 된다.
  if not exists (
    select 1
    from storage.objects as object
    where object.bucket_id = 'story-media'
      and object.name = story.thumbnail_path
      and object.owner_id = caller_id::text
      and object.metadata ->> 'mimetype' = 'image/webp'
  ) then
    raise exception 'uploaded thumbnail not found' using errcode = 'P0002';
  end if;

  update public.stories
  set status = 'ready',
    published_at = published,
    expires_at = published + interval '24 hours'
  where id = story.id;
end;
$function$;

ALTER TABLE "private"."storage_cleanup_queue"
  ADD CONSTRAINT "storage_cleanup_queue_reason_check"
    CHECK
    ((reason = ANY (ARRAY['post_attachment'::text, 'comment_image'::text, 'group_media'::text, 'profile_media'::text, 'profile_media_activity'::text, 'story_media'::text,
    'unreferenced_sweep'::text])));

CREATE VIEW "private"."referenced_storage_objects" AS  SELECT 'profile-media'::text AS bucket,
    profile.avatar_path AS object_path
   FROM public.profiles profile
  WHERE (profile.avatar_path IS NOT NULL)
UNION ALL
 SELECT 'profile-media'::text AS bucket,
    profile.cover_path AS object_path
   FROM public.profiles profile
  WHERE (profile.cover_path IS NOT NULL)
UNION ALL
 SELECT 'profile-media'::text AS bucket,
    post.activity_media_path AS object_path
   FROM public.posts post
  WHERE (post.activity_media_path IS NOT NULL)
UNION ALL
 SELECT 'profile-media'::text AS bucket,
    media.object_path
   FROM public.profile_media_objects media
UNION ALL
 SELECT 'profile-media'::text AS bucket,
    activity.object_path
   FROM public.profile_media_activity_objects activity
UNION ALL
 SELECT attachment.storage_bucket AS bucket,
    attachment.object_path
   FROM public.post_attachments attachment
UNION ALL
 SELECT attachment.storage_bucket AS bucket,
    attachment.thumbnail_path AS object_path
   FROM public.post_attachments attachment
  WHERE (attachment.thumbnail_path IS NOT NULL)
UNION ALL
 SELECT image.storage_bucket AS bucket,
    image.object_path
   FROM public.comment_images image
UNION ALL
 SELECT 'group-media'::text AS bucket,
    media.object_path
   FROM public.group_media_objects media
UNION ALL
 SELECT 'story-media'::text AS bucket,
    story.image_path AS object_path
   FROM public.stories story
  WHERE (story.image_path IS NOT NULL)
UNION ALL
 SELECT 'story-media'::text AS bucket,
    story.thumbnail_path AS object_path
   FROM public.stories story
  WHERE (story.thumbnail_path IS NOT NULL);

CREATE POLICY "story_media_storage_insert_pending_author" ON "storage"."objects"
  FOR INSERT
  TO "authenticated"
  WITH CHECK (((bucket_id = 'story-media'::text) AND (owner_id = ( SELECT (auth.uid())::text AS uid)) AND private.can_upload_story_media(name)));

CREATE POLICY "story_media_storage_select_reader" ON "storage"."objects"
  FOR SELECT
  TO "authenticated"
  USING
    (((bucket_id = 'story-media'::text) AND storage.allow_any_operation(ARRAY['object.get_authenticated_info'::text, 'object.get_authenticated'::text, 'object.sign'::text,
    'object.sign_many'::text]) AND private.can_read_story_media(name)));

REVOKE ALL ON FUNCTION "private"."can_read_story"(bigint) FROM PUBLIC;

GRANT EXECUTE ON FUNCTION "private"."can_read_story"(bigint) TO "postgres";

REVOKE ALL ON FUNCTION "private"."can_read_story_media"(text) FROM PUBLIC;

GRANT EXECUTE ON FUNCTION "private"."can_read_story_media"(text) TO "authenticated", "postgres";

REVOKE ALL ON FUNCTION "private"."can_upload_story_media"(text) FROM PUBLIC;

GRANT EXECUTE ON FUNCTION "private"."can_upload_story_media"(text) TO "authenticated", "postgres";

REVOKE ALL ON FUNCTION "private"."story_writer_profile_id"() FROM PUBLIC;

GRANT EXECUTE ON FUNCTION "private"."story_writer_profile_id"() TO "postgres";

REVOKE ALL ON FUNCTION "public"."create_text_story"(text, text, text) FROM PUBLIC;

GRANT EXECUTE ON FUNCTION "public"."create_text_story"(text, text, text) TO "authenticated", "postgres";

REVOKE ALL ON FUNCTION "public"."delete_my_story"(bigint) FROM PUBLIC;

GRANT EXECUTE ON FUNCTION "public"."delete_my_story"(bigint) TO "authenticated", "postgres";

REVOKE ALL ON FUNCTION "public"."list_active_stories"() FROM PUBLIC;

GRANT EXECUTE ON FUNCTION "public"."list_active_stories"() TO "authenticated", "postgres";

REVOKE ALL ON FUNCTION "public"."prepare_image_story"(bigint, integer, integer, text, text) FROM PUBLIC;

GRANT EXECUTE ON FUNCTION "public"."prepare_image_story"(bigint, integer, integer, text, text) TO "authenticated", "postgres";

REVOKE ALL ON FUNCTION "public"."publish_image_story"(bigint) FROM PUBLIC;

GRANT EXECUTE ON FUNCTION "public"."publish_image_story"(bigint) TO "authenticated", "postgres";

GRANT USAGE ON TYPE "public"."story_status" TO "postgres";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "private"."referenced_storage_objects" TO "postgres";
