import type { Conversation } from "~/features/messaging/model/types";

const viewer = {
  id: "viewer",
  name: "김한결",
  avatarUrl: null,
};

export const mockConversations: Conversation[] = [
  {
    id: "student-council",
    type: "group",
    name: "학생회 기획부",
    participants: [
      viewer,
      { id: "seo", name: "박서현", avatarUrl: null },
      { id: "min", name: "최민준", avatarUrl: null },
      { id: "ji", name: "윤지우", avatarUrl: null },
    ],
    lastMessage: "서현: 내일 점심시간에 최종 확인할게요!",
    lastActivityLabel: "12분",
    unreadCount: 3,
    muted: false,
    sharedMediaCount: 18,
    sharedFileCount: 6,
    sharedLinkCount: 9,
    messages: [
      {
        id: "m1",
        senderId: null,
        body: "박서현님이 대화 이름을 ‘학생회 기획부’로 변경했습니다.",
        sentAt: "오후 3:08",
        dayLabel: "2026년 8월 28일 금요일",
        system: true,
      },
      {
        id: "m2",
        senderId: "seo",
        body: "축제 부스 배치 초안 확인했어요?",
        sentAt: "오후 3:12",
      },
      {
        id: "m3",
        senderId: "seo",
        body: "수정할 부분 있으면 오늘 안에 알려주세요.",
        sentAt: "오후 3:12",
        reactions: [{ reaction: "like", count: 3 }],
      },
      {
        id: "m4",
        senderId: "viewer",
        body: "확인했습니다! 2층 체험 부스 동선만 조금 넓히면 좋을 것 같아요.",
        sentAt: "오후 3:18",
        readBy: ["서현", "민준", "지우"],
      },
      {
        id: "m5",
        senderId: "min",
        body: "관련 자료는 여기에도 정리해 두었어요.\nhttps://www.kmlaonline.net",
        sentAt: "오후 3:25",
        pinned: true,
      },
      {
        id: "m6",
        senderId: "viewer",
        body: "고마워요 🙌",
        sentAt: "오후 3:31",
        readBy: ["서현"],
      },
      {
        id: "m7",
        senderId: "seo",
        body: "내일 점심시간에 최종 확인할게요!",
        sentAt: "오후 3:36",
      },
    ],
  },
  {
    id: "hyunwoo",
    type: "direct",
    name: "이현우",
    participants: [
      viewer,
      { id: "hyunwoo-user", name: "이현우", avatarUrl: null },
    ],
    lastMessage: "좋아, 도서관 앞에서 보자",
    lastActivityLabel: "35분",
    unreadCount: 0,
    muted: false,
    sharedMediaCount: 7,
    sharedFileCount: 2,
    sharedLinkCount: 3,
    messages: [
      {
        id: "h1",
        senderId: "hyunwoo-user",
        body: "오늘 자습 끝나고 잠깐 볼 수 있어?",
        sentAt: "오후 2:41",
        dayLabel: "2026년 8월 28일 금요일",
      },
      {
        id: "h2",
        senderId: "viewer",
        body: "응, 9시쯤이면 괜찮아.",
        sentAt: "오후 2:43",
        readBy: ["현우"],
      },
      {
        id: "h3",
        senderId: "hyunwoo-user",
        body: "좋아, 도서관 앞에서 보자",
        sentAt: "오후 2:44",
      },
    ],
  },
  {
    id: "science-project",
    type: "group",
    name: "과학전람회 준비",
    participants: [
      viewer,
      { id: "eun", name: "정은재", avatarUrl: null },
      { id: "ha", name: "송하린", avatarUrl: null },
    ],
    lastMessage: "은재: 실험 결과 파일 올렸습니다",
    lastActivityLabel: "1시간",
    unreadCount: 1,
    muted: true,
    sharedMediaCount: 4,
    sharedFileCount: 12,
    sharedLinkCount: 2,
    messages: [
      {
        id: "s1",
        senderId: "eun",
        body: "실험 결과 파일 올렸습니다",
        sentAt: "오후 1:54",
        dayLabel: "2026년 8월 28일 금요일",
      },
    ],
  },
  {
    id: "room-203",
    type: "group",
    name: "203호",
    participants: [
      viewer,
      { id: "jun", name: "강준호", avatarUrl: null },
      { id: "ye", name: "김예린", avatarUrl: null },
      { id: "do", name: "남도윤", avatarUrl: null },
    ],
    lastMessage: "도윤: 우산 주인 찾았습니다 ☂️",
    lastActivityLabel: "3시간",
    unreadCount: 0,
    muted: false,
    sharedMediaCount: 22,
    sharedFileCount: 1,
    sharedLinkCount: 5,
    messages: [
      {
        id: "r1",
        senderId: "do",
        body: "우산 주인 찾았습니다 ☂️",
        sentAt: "오전 11:22",
        dayLabel: "2026년 8월 28일 금요일",
      },
    ],
  },
  {
    id: "broadcasting",
    type: "group",
    name: "방송부",
    participants: [
      viewer,
      { id: "su", name: "한수빈", avatarUrl: null },
      { id: "jae", name: "오재원", avatarUrl: null },
    ],
    lastMessage: "재원: 다음 주 방송 순서 공유할게요",
    lastActivityLabel: "어제",
    unreadCount: 0,
    muted: false,
    sharedMediaCount: 35,
    sharedFileCount: 8,
    sharedLinkCount: 11,
    messages: [
      {
        id: "b1",
        senderId: "jae",
        body: "다음 주 방송 순서 공유할게요",
        sentAt: "오후 8:10",
        dayLabel: "2026년 8월 27일 목요일",
      },
    ],
  },
];
